### ISSUE TITLE
Builds with make -j not working

### ISSUE THREAD

**Issue by edhartnett** [gptl/GPTL-fortran#7]
Make check works, but make -j check does not.

Some dependency is not being tracked, which needs to be.

**Comment by jmrosinski** [comment]
Interesting. I generally don't build GPTL with "-j" since it builds so
quickly. But I agree this should work. Let's put this at lower priority for
now--I'll see if it works in the old stuff and we can go from there.

**Comment by edhartnett** [comment]
Whether it works in the old build is not really relevant.

When make -j does not work, it is also a sign that a dependency is not being tracked properly by the build system. So it's not just a question of faster builds, it means something is not correct.

I suspect that it's because there is currently no tracking of the .mod file. I will investigate and fix.

**Comment by jmrosinski** [comment]
I think I see what you're saying--it's working without "-j" probably due to
something superfluous like something starting with "b" depending on
something starting with "a", and "a" gets compiled before "b" just due to
its name. It would break if the "a" thing changed its name to "c". Is that
right?

**Comment by edhartnett** [comment]
Added dependency on the mod files as suggested, and that solved the -j problem.

**Comment by edhartnett** [comment]
Not working again! 

```
make[1]: *** No rule to make target 'gptl.mod', needed by 'all-am'.  Stop.
make[1]: *** Waiting for unfinished jobs....
```
